RetrievePackage/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

RetrievePackage/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Block_Credit_Card_Number__c</fullName>
        <label>Block Credit Card Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Card</label>
        <referenceTo>Credit_Card__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Email__c</fullName>
        <label>Customer Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

RetrievePackage/objects/Credit_Card__c.object
<CustomObject>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Card</label>
    <nameField>
        <label>Credit Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AcctsTest.cls
@isTest
public class AcctsTest{
    
    

    public static testmethod void createCaseTest(){
    
       Account act  = new Account();
       act.Name = 'test';
       act.Phone = '+17607058888';
       act.Email__c = 'ajay@gmail.com';
              
       insert act;
       
       Contact ct = new Contact();
       ct.LastName = 'Test';
       ct.Phone = '(760) 705-8888';
       ct.AccountId = act.id;
       insert ct;
       
       Credit_Card__c crd = new Credit_Card__c();
       crd.Card_Number__c = '1234';
       crd.Name__c = act.id;
       insert crd;
       Acctsinfo.createCase('test','New','Phone','Credit Card Lost','High',act.id,ct.id,'1234','ajay@gmail.com');
      // Accts.upsertCase('testing','Escalated','Email','Medium',cs.id,'New Account');
      // upsert cs;
       Case cs = new Case();
       cs.Subject = 'test';
       cs.Status = 'New';
       cs.Origin = 'Phone';
       cs.Type = 'Credit Card Lost';
       cs.Priority = 'High';
       cs.AccountId = act.id;
       cs.ContactId = ct.id;
       cs.Block_Credit_Card_Number__c  = '1234';
       cs.Customer_Email__c  = 'ajay@gmail.com';
       upsert cs;
       Acctsinfo.upsertCase('testing','Escalated','Email','Medium',cs.id,'New Account');      
    }

   
}