RetrievePackage/objects/Credit_Card__c.object
<CustomObject>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Card</label>
    <nameField>
        <label>Credit Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetrievePackage/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Card</label>
        <referenceTo>Credit_Card__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Of_Transaction__c</fullName>
        <label>Date Of Transaction</label>
        <type>Date</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetrievePackage/classes/TransTotal.cls
@RestResource(urlMapping='/TotalTransactions/*')
global with sharing class TransTotal{
    
    @HttpGet
    global static Integer getTrans() {
    
        Integer cnt;
        RestRequest request = RestContext.request;
        // grab the caseId from the end of the URL
      /* String credId = request.requestURI.substring(
            request.requestURI.lastIndexOf('/')+1); */
            
       string actId = request.requestURI.substringBetween('/AccountransId/', '/Crdnum/');
        string credId = request.requestURI.substringAfter('/Crdnum/');
        
        
        /*Credit_Card__c  credres =  [select id,Card_Number__c,(select Amount__c,Date_Of_Transaction__c,Description__c from Transactions__r) from Credit_Card__c where Card_Number__c = :credId LIMIT 1];
        Transaction__c trns = [select count() from Transaction__c];
        return credres;*/
        
        List<Credit_Card__c > credes= [select id,Card_Number__c,(select id from Transactions__r where Date_Of_Transaction__c> :DateTime.now().addHours(-48).date()  ) from Credit_Card__c where Name__c=:actId and Card_Number__c = :credId];
        system.debug(credes);
        for (Credit_Card__c crds: credes) {
    // do something with it...
         
        cnt = crds.Transactions__r.size();
        
        
        
}
        //system.debug(crds.Transactions__r.size());
        system.debug(cnt); 
   return cnt;
    
    }
 }