RetrievePackage/objects/Credit_Card__c.object
<CustomObject>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Card</label>
    <nameField>
        <label>Credit Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetrievePackage/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Card</label>
        <referenceTo>Credit_Card__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Of_Transaction__c</fullName>
        <label>Date Of Transaction</label>
        <type>Date</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetrievePackage/classes/TransTest.cls
@isTest
public class TransTest{
    
    public static testmethod void testTransaction(){
        
       Credit_Card__c crd = new Credit_Card__c();
       crd.Card_Number__c = '1234';
       //crd.Name__c = act.id;
       insert crd;
       
      Transaction__c trns = new Transaction__c();
      trns.Date_Of_Transaction__c = Date.today()-2;
      trns.Credit_Card__c = crd.id;
      insert trns;
      
     Id recordId = trns.id;
   RestRequest request = new RestRequest();
   request.requestUri ='https://financialcloud-dev-ed.my.salesforce.com/services/apexrest/TotalTransactions/Crdnum'+recordId;

     request.httpMethod = 'GET';
     RestContext.request = request;
     TransTotal.getTrans();
             
        
    }


}